import { useEffect, useState } from 'react';
import Icon from './components/Icon';
import { education } from './data/education';
import { technologies } from './data/technologies';
import { fallbackProjects, getProjects } from './data/projects';

const github = 'https://github.com/NDHBBCYED';
const linkedin = 'https://www.linkedin.com/in/francisco-clemente-batista-s%C3%A1nchez-832b85273/';
const nav = [['Inicio', 'inicio'], ['Sobre mí', 'sobre-mi'], ['Historia', 'historia'], ['Formación', 'formacion'], ['Tecnologías', 'tecnologias'], ['Proyectos', 'proyectos'], ['Contacto', 'contacto']];

function LinkButton({ href, children, variant = 'primary', icon }) { return <a className={`button ${variant}`} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer">{children}{icon && <Icon name={icon} size={16}/>}</a>; }
function SectionTitle({ eyebrow, title, text }) { return <header className="section-title reveal"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</header>; }

export default function App() {
  const [dark, setDark] = useState(() => localStorage.getItem('theme') !== 'light');
  const [menu, setMenu] = useState(false); const [projects, setProjects] = useState(fallbackProjects); const [filter, setFilter] = useState('Todos'); const [loading, setLoading] = useState(false);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('theme', dark ? 'dark' : 'light'); }, [dark]);
  useEffect(() => { getProjects().then(setProjects); }, []);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach(e => e.isIntersecting && e.target.classList.add('visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); return () => observer.disconnect(); }, [projects]);
  const visible = filter === 'Todos' ? projects : projects.filter((p) => {
    const searchable = `${p.name} ${p.description} ${p.language} ${p.tags.join(' ')}`.toLowerCase();
    if (filter === 'Front-End') return /html|css|javascript|typescript|frontend|front-end|vite|bootstrap/.test(searchable);
    if (filter === 'React') return /react|jsx|tsx/.test(searchable);
    if (filter === 'Bases de datos') return /sql|mysql|database|base-de-datos|firebase|mongo/.test(searchable);
    if (filter === 'Otros') return !/html|css|javascript|typescript|react|sql|mysql|firebase/.test(searchable);
    return searchable.includes(filter.toLowerCase());
  });
  const navigate = (id) => { setMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  return <><header className="nav"><a className="brand" href="#inicio">FC<span>.</span></a><nav className={menu ? 'open' : ''}>{nav.map(([label,id]) => <button key={id} onClick={() => navigate(id)}>{label}</button>)}<a href={github} target="_blank" rel="noreferrer" className="nav-social"><Icon name="github"/> GitHub</a></nav><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Cambiar tema"><Icon name="sun"/></button><button className="menu icon-button" onClick={() => setMenu(!menu)} aria-label="Abrir menú"><Icon name={menu ? 'close' : 'menu'}/></button></div></header>
  <main>
    <section id="inicio" className="hero"><div className="hero-copy reveal visible"><span className="availability"><i/> Disponible para aprender y colaborar</span><p className="hero-label">Hola, soy</p><h1>Francisco<br/><em>Clemente.</em></h1><h2>Estudiante de Ingeniería en Desarrollo de Software</h2><p className="lead">Tecnólogo en Desarrollo de Software · ITLA</p><p className="intro">Construyo proyectos web y de software mientras continúo creciendo como desarrollador.</p><div className="actions"><LinkButton href="#proyectos" icon="arrow">Ver mis proyectos</LinkButton><LinkButton href="#historia" variant="secondary">Conocer mi historia</LinkButton></div><div className="social-links"><a href={github} target="_blank" rel="noreferrer"><Icon name="github"/> GitHub</a><a href={linkedin} target="_blank" rel="noreferrer"><Icon name="linkedin"/> LinkedIn</a></div></div><div className="portrait reveal visible"><div className="portrait-note">República<br/>Dominicana <span>↗</span></div><img src="/profile.jpg" alt="Francisco Clemente Batista Sánchez"/><div className="portrait-tag">Software<br/>in progress <i/></div></div></section>
    <section id="sobre-mi" className="about grid-section"><SectionTitle eyebrow="02" title="Sobre mí"/><div className="about-text reveal"><p className="large">Soy Francisco Clemente Batista Sánchez, Tecnólogo en Desarrollo de Software egresado del Instituto Tecnológico de las Américas (ITLA) y actualmente estudiante de Ingeniería en Desarrollo de Software en UNICARIBE.</p><p>Mi interés por la tecnología me ha llevado a desarrollar proyectos, experimentar con diferentes herramientas y continuar ampliando mis conocimientos en desarrollo de software y desarrollo web.</p><p>Realicé una pasantía como Analista de Sistemas de Información en la Dirección General de Minería, una experiencia que reforzó mi interés por crear soluciones útiles.</p></div></section>
    <section id="historia" className="timeline-section"><SectionTitle eyebrow="02 — RECORRIDO" title={<>Mi camino en <em>tecnología.</em></>} text="Una formación que se construye con curiosidad, práctica y la decisión de seguir avanzando."/><div className="timeline">{[['01','El comienzo','El interés por el software, la programación y el desarrollo web marcó el inicio de un camino de aprendizaje constante.'],['02','ITLA','Una etapa clave para fortalecer conocimientos en programación, desarrollo web, bases de datos, análisis de sistemas y creación de aplicaciones.'],['03','Crear proyectos','Aprender haciendo: experimentar con herramientas, resolver problemas y convertir ideas en aplicaciones.'],['04','UNICARIBE','Después de egresar como Tecnólogo, continúo mi formación académica en Ingeniería en Desarrollo de Software.'],['05','Lo que sigue','Continuar fortaleciendo mis conocimientos, desarrollar proyectos cada vez más completos y construir experiencia profesional.']].map(([number,title,text]) => <article className="timeline-item reveal" key={number}><span className="number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section id="formacion" className="education"><SectionTitle eyebrow="03 — FORMACIÓN" title="Una base que sigue creciendo."/><div className="education-path reveal">{education.map((item,i) => <div className="education-card" key={item.school}><span>{item.year}</span><p className="school">{item.school}</p><h3>{item.degree}</h3><p>{item.name}</p><b>{item.status}</b>{i === 0 && <div className="progress-arrow">→</div>}</div>)}</div><p className="education-statement reveal">Tecnólogo <span>→</span> Ingeniería</p></section>
    <section id="tecnologias" className="technologies"><SectionTitle eyebrow="04 — HERRAMIENTAS" title="Tecnologías y herramientas" text="Conocimientos adquiridos a través de mi formación y proyectos."/><div className="tech-grid">{technologies.map(([group,items],i) => <article className="tech-card reveal" key={group}><span>0{i+1}</span><h3>{group}</h3><div>{items.map(item => <b key={item}>{item}</b>)}</div><small>{i < 2 ? 'Conocimientos' : i === 4 ? 'En práctica' : 'Actualmente aprendiendo'}</small></article>)}</div></section>
    <section id="proyectos" className="projects"><SectionTitle eyebrow="05 — PORTAFOLIO" title={<>Proyectos que ponen en práctica <em>lo aprendido.</em></>}/><div className="filters reveal">{['Todos','Front-End','JavaScript','React','Bases de datos','Otros'].map(item => <button onClick={() => setFilter(item)} className={filter === item ? 'active' : ''} key={item}>{item}</button>)}</div>{loading ? <p className="loading">Cargando repositorios desde GitHub…</p> : visible.length ? <div className="project-grid">{visible.map(project => <article className="project-card reveal" key={project.id}><div className="project-top"><span className="code-mark">&lt;/&gt;</span><span>Actualizado {project.updated}</span></div><h3>{project.name.replaceAll('-', ' ')}</h3><p>{project.description}</p><div className="project-foot"><b>{project.language}</b><div><a href={project.demo || project.url} target="_blank" rel="noreferrer">Ver proyecto ↗</a><a href={project.url} target="_blank" rel="noreferrer">Código <Icon name="arrow" size={14}/></a></div></div></article>)}</div> : <div className="empty">No hay proyectos públicos que coincidan con este filtro. <a href={github}>Explorar GitHub →</a></div>}</section>
    <section className="github-callout reveal"><div><span className="eyebrow">06 — GITHUB</span><h2>Explora mi código.</h2><p>Una gran parte de mi aprendizaje ocurre construyendo proyectos. En GitHub puedes conocer algunos de los proyectos que he desarrollado y ver cómo continúo evolucionando.</p></div><LinkButton href={github} variant="light" icon="github">Ver GitHub</LinkButton></section>
    <section id="contacto" className="contact"><span className="eyebrow">07 — CONTACTO</span><h2>¿Hablamos?</h2><p>Estoy interesado en continuar creciendo en el área de tecnología, conocer nuevas oportunidades, colaborar en proyectos y seguir desarrollándome profesionalmente.</p><div className="contact-links"><LinkButton href={linkedin} icon="linkedin">Visitar LinkedIn</LinkButton><LinkButton href={github} variant="secondary" icon="github">GitHub</LinkButton></div></section>
  </main><footer><a className="brand" href="#inicio">FC<span>.</span></a><p>Diseñado y construido por Francisco Clemente © {new Date().getFullYear()}</p><a href="#inicio">Volver arriba ↑</a></footer></>;
}
